#!/usr/bin/env bash

# Function to display information about a subdomain
domain_information() {
    local domain="$1"
    local subdomain="$2"
    local record_type
    local destination
    local answer_section

    answer_section=$(dig +short "$subdomain.$domain" | grep -A1 'ANSWER SECTION:')
    record_type=$(echo "$answer_section" | grep -oP '\b[A-Z]+\b' | tail -1)
    destination=$(echo "$answer_section" | grep -oP '\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b')

    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Main part
if [ "$#" -eq 1 ]; then
    domain_information "$1" "www"
    domain_information "$1" "lb-01"
    domain_information "$1" "web-01"
    domain_information "$1" "web-02"
elif [ "$#" -eq 2 ]; then
    domain_information "$1" "$2"
else
    echo "Usage: $0 <domain> [<subdomain>]"
    exit 1
fi
