#!/usr/bin/env bash
# This script kills the process 7-highlander

# Find the PID of the process
pid=$(pgrep -f "7-highlander")

# Check if the process is running
if [ -n "$pid" ]; then
  # Kill the process
  kill "$pid"
  echo "Process killed"
else
  echo "Process not found"
fi
